version: '3.8'

services:
  api:
    build: .
    container_name: raspberry-api
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    command: npm start